# Generated by Django 5.1.5 on 2025-04-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address", models.TextField()),
                ("opening_time", models.TimeField()),
                ("closing_time", models.TimeField()),
            ],
        ),
    ]
