# Generated by Django 5.1.5 on 2025-04-17 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0003_food_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food_selection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="food_rush.food_item",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now=True)),
                ("eta", models.DateTimeField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_rush.customer",
                    ),
                ),
                (
                    "food",
                    models.ManyToManyField(
                        related_name="orders",
                        through="food_rush.Food_selection",
                        to="food_rush.food_item",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="food_rush.restaurant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="food_selection",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="food_rush.order"
            ),
        ),
    ]
