# Generated by Django 5.1.5 on 2025-04-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0004_food_selection_order_food_selection_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="eta",
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(editable=False),
        ),
    ]
