# Generated by Django 5.1.5 on 2025-04-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0005_alter_order_eta_alter_order_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="profile_photo_url",
            field=models.URLField(blank=True),
        ),
    ]
