# Generated by Django 5.1.5 on 2025-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0006_restaurant_profile_photo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="profile_photo_url",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="profile_photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
