# Generated by Django 4.2.20 on 2025-04-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_rush', '0008_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_selection',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
            preserve_default=False,
        ),
    ]
