# Generated by Django 5.1.5 on 2025-04-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0012_alter_food_selection_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="food_item",
            name="food_photo",
            field=models.ImageField(blank=True, upload_to=""),
        ),
    ]
