# Generated by Django 5.1.5 on 2025-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_rush", "0013_food_item_food_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="address",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
