# Generated by Django 5.1.5 on 2025-04-03 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("address_street_number", models.TextField()),
                ("address_street_name", models.TextField()),
                ("address_apt_number", models.TextField()),
                ("zip_code", models.IntegerField()),
                ("dob", models.DateField()),
                ("reg_date", models.DateField()),
                ("party", models.CharField(max_length=2)),
                ("precint_number", models.IntegerField()),
                ("v20", models.TextField()),
                ("v21_t", models.TextField()),
                ("v21_p", models.TextField()),
                ("v22", models.TextField()),
                ("v23", models.TextField()),
                ("voter_score", models.IntegerField()),
            ],
        ),
    ]
